name: "Test Insertion"
description: Issues to create automated tests for an existing feature.
title: "`[TEST]` - Title"
projects: ["odavibatista/14"]
assignees: "odavibatista"
labels: ["tests"]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: How risky is this feature?
      options:
        - label: Riskless
          required: false
        - label: Low
          required: false
        - label: Medium
          required: false
        - label: High
          required: false